<?php

//namespace io;

import("io.IOException");

/**
 * Thrown when an error code is generated by php when uploading a file.
 * 
 * @exception 
 * @package io
 * @author Demián Andrés Rodriguez (demian85@gmail.com)
 */
class FileUploadException extends IOException
{
	protected $uploadErrorCode;
	
	/**
	 * Constructor.
	 *
	 * @param int $code
	 * @param string $message
	 */
	function __construct($code, $message = '')
	{
		switch ($code) {
			case UPLOAD_ERR_INI_SIZE:
				$msg = "The uploaded file exceeds the upload_max_filesize directive in php.ini.";
				break;
			case UPLOAD_ERR_FORM_SIZE:
				$msg = "The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form.";
				break;
			case UPLOAD_ERR_PARTIAL:
				$msg = "The uploaded file was only partially uploaded.";
				break;
			case UPLOAD_ERR_NO_FILE:
				$msg = "No file was uploaded.";
				break;
			case UPLOAD_ERR_NO_TMP_DIR:
				$msg = "Missing a temporary folder.";
				break;
			case UPLOAD_ERR_CANT_WRITE:
				$msg = "Failed to write file to disk.";
				break;
			case UPLOAD_ERR_EXTENSION:
				$msg = "File upload stopped by extension.";
				break;
			default:
				$msg = "";
		}
		
		if ($message) $msg .= " " . $message;
		
		parent::__construct($msg);
		
		$this->uploadErrorCode = (int)$code;
	}
}
?>
